CREATE TABLE spiders (
    record VARCHAR(6) DEFAULT 'RECORD',
    id TEXT,
    type VARCHAR(15) NOT NULL,
    modified VARCHAR(15),
    language0 VARCHAR(15),
    license VARCHAR(15) NOT NULL,
    rightsholder TEXT,
    references0 TEXT,
    bibliographiccitation TEXT,
    institutionid TEXT,
    institutioncode TEXT,
    ownerinstitutioncode TEXT,
    collectioncode TEXT,
    datasetname TEXT,
    basisofrecord VARCHAR(20) NOT NULL,
    dynamicproperties TEXT,
    occurrence VARCHAR(10) DEFAULT 'OCCURRENCE',
    occurrencestatus VARCHAR(15) NOT NULL,
    disposition VARCHAR(15),
    occurrenceid TEXT NOT NULL,
    catalognumber TEXT,
    recordedby TEXT,
    individualcount INT,
    organismquantity DOUBLE,
    organismquantitytype TEXT,
    sex VARCHAR(100),
    lifestage VARCHAR(100),
    associatedreferences TEXT,
    associatedtaxa TEXT,
    establishmentmeans VARCHAR(35),
    occurrenceremarks TEXT
    event VARCHAR(5) DEFAULT 'EVENT',
    eventid VARCHAR(100),
    parenteventid VARCHAR(100),
    fieldnumber VARCHAR(100),
    eventdate VARCHAR(25),
    startdayofyear INT,
    enddayofyear INT,
    year0 INT,
    month0 INT,
    day0 INT,
    verbatimeventdate VARCHAR(100),
    habitat TEXT,
    samplingprotocol TEXT,
    samplingeffort TEXT,
    samplesizevalue DOUBLE,
    samplesizeunit VARCHAR(100),
    eventremarks TEXT,
    location VARCHAR(10) DEFAULT 'LOCATION',
    locationid VARCHAR(100),
    highergeography VARCHAR(100),
    continent VARCHAR(30),
    country VARCHAR(30),
    countrycode VARCHAR(3),
    stateprovince VARCHAR(100),
    county VARCHAR(100),
    municipality VARCHAR(100),
    locality TEXT,
    verbatimlocality TEXT,
    minimumelevationinmeters INT,
    maximumelevationinmeters INT,
    decimallatitude DOUBLE,
    decimallongitude DOUBLE,
    geodeticdatum VARCHAR(30),
    coordinateuncertaintyinmeters INT,
    coordinateprecision DOUBLE,
    verbatimCoordinates VARCHAR(50),
    georeferencedby VARCHAR(30),
    georeferenceddate VARCHAR(10),
    locationremarks TEXT,
    identification VARCHAR(15) DEFAULT 'IDENTIFICATION',
    identifiedby VARCHAR(30),
    dateidentified VARCHAR(10),
    verbatimidentification VARCHAR(50),
    identificationremarks TEXT,
    taxon VARCHAR(5) DEFAULT 'TAXON',
    taxonrank VARCHAR(10),
    scientificname VARCHAR(100) NOT NULL,
    kingdom VARCHAR(10) DEFAULT 'Animalia',
    phylum VARCHAR(10) DEFAULT 'Arthropoda',
    class VARCHAR(10) DEFAULT 'Arachnida',
    order0 VARCHAR(10),
    family VARCHAR(30),
    genus VARCHAR(30),
    specificepithet VARCHAR(30),
    scientificnameauthorship VARCHAR(100),
    canonicalname VARCHAR(100),
    acceptednameusage VARCHAR(100),
    type_status VARCHAR(30),
    taxonRemarks TEXT,
    remove VARCHAR(6) DEFAULT 'REMOVE',
    publ_id INT NOT NULL,
    vol_ids TEXT
);
